services:
  limboo-cards-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./src:/app
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_HOST_PATH=/usr/share/dotnet/dotnet
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
    depends_on:
      - nats
      - postgres
    networks:
      - limboo-network
    command: ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:5000"]

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command: -js
    volumes:
      - nats_data:/data
    networks:
      - limboo-network

  postgres:
    image: postgres:15
    container_name: limboo-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: limboocardsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - limboo-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: limboo-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "True"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - limboo-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  nats_data:
  postgres_data:
  pgadmin_data:

networks:
  limboo-network:
    driver: bridge