services:
  limboo-cards-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./src:/app
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_HOST_PATH=/usr/share/dotnet/dotnet
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
      - SUBJECT_GETBYID_URL=https://031cb4f312dfee4b918aa9feefe9fd.e8.environment.api.powerplatform.com/powerautomate/automations/direct/workflows/f596f122f19b41e9ba64bc4900fd1413/triggers/manual/paths/invoke/subject?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=yffQm7RxLz7duL3NHk3ZWEW6eadPXeHcnuNCgwCfG4M
      - SUBJECT_GETALL_URL=https://031cb4f312dfee4b918aa9feefe9fd.e8.environment.api.powerplatform.com/powerautomate/automations/direct/workflows/d3b43b4cd2e642fbbdfc859a9a701865/triggers/manual/paths/invoke/subjects?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=xMAMqt2lLsY40w1whH2_0_UamIA5VtLuai5N7vQAFFI
      - SUBJECT_GETPAGED_URL=https://031cb4f312dfee4b918aa9feefe9fd.e8.environment.api.powerplatform.com/powerautomate/automations/direct/workflows/e0b679a50103403a879ef4af9b3da0fd/triggers/manual/paths/invoke/subjects?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=XYv1fIFiKUYowFXZU7E1R9yuK_hLlS5WFm2mxoBSt2Y
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
    networks:
      - limboo-network
    command: ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:5000"]

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command: -js
    volumes:
      - nats_data:/data
    networks:
      - limboo-network

volumes:
  nats_data:

networks:
  limboo-network:
    driver: bridge