FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app

COPY src/*.csproj ./

RUN dotnet restore

COPY src/ ./

EXPOSE 5000
EXPOSE 5001

CMD ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:5000"]
