global using Xunit;
global using LimbooCards.Domain.Entities;
global using LimbooCards.Domain.Events;
global using LimbooCards.Domain.Services;
global using AutoMapper;
global using LimbooCards.Application.DTOs;
global using LimbooCards.Application.Services;
global using LimbooCards.Domain.Repositories;
global using Moq;